# Generated by Django 4.0.3 on 2022-03-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='catagories'),
        ),
    ]
