# Generated by Django 4.0.3 on 2022-03-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_catagories_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture_for_mini_items',
            field=models.ImageField(default='default.jpg', upload_to='products'),
        ),
    ]
