# Generated by Django 4.0.3 on 2022-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
