# Generated by Django 4.0.3 on 2022-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='blogs/images'),
        ),
    ]
