# Generated by Django 4.0.3 on 2022-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtext',
            field=models.TextField(blank=True),
        ),
    ]
